/* 論文・総説データ — publications.html と index.html で共有 */
/* このファイルを更新するだけで両ページに自動反映される */

const papers = [
  {n:1,  y:1995, au:"Sasaki T, Hazeki K, Hazeki O, Ui M, Katada T",
   ti:"Permissive effect of ceramide on growth factor-induced cell proliferation",
   jo:"Biochem J", vp:"311:829-834", doi:"10.1042/bj3110829"},
  {n:2,  y:1996, au:"Sasaki T, Hazeki K, Hazeki O, Ui M, Katada T",
   ti:"Focal adhesion kinase (p125FAK) and paxillin are substrates for sphingomyelinase-induced tyrosine phosphorylation in Swiss 3T3 fibroblasts",
   jo:"Biochem J", vp:"315:1035-1040", doi:"10.1042/bj3151035"},
  {n:3,  y:1997, au:"Yao Z, Dinner K, Wang X, Zukowski M, Matsumoto G, Zhou G, Mo R, Sasaki T, Nishina H, Hui C, Tan T, Woodgett J, Penninger J",
   ti:"Activation of stress-activated protein kinase/c-Jun N-terminal protein kinases (SAPKs/JNKs) by a novel mitogen-activated protein kinase kinase (MKK7)",
   jo:"J Biol Chem", vp:"272:32378-32383", doi:"10.1074/jbc.272.51.32378"},
  {n:4,  y:1998, au:"Fischer K, Kong Y, Nishina H, Tedford K, Merengere L, Kozieradzki I, Sasaki T, Starr M, Chan G, Gardner S, Nghiem M, Bouchard D, Barbacid M, Bernstein A, Penninger J",
   ti:"Vav is a regulator of cytoskeletal reorganization mediated by the T-cell receptor",
   jo:"Curr Biol", vp:"8:554-562", doi:"10.1016/s0960-9822(98)70224-6"},
  {n:5,  y:1998, au:"Nishina H, Radcanyi L, Raju K, Sasaki T, Kozieradzki I, Penninger J",
   ti:"Impaired TCR-mediated apoptosis and Bcl-XL expression in T cells lacking the stress kinase activator SEK1/MKK4",
   jo:"J Immunol", vp:"161:3416-3420", doi:""},
  {n:6,  y:1998, au:"Stambolic V, Suzuki A, Pompa J, Brothers G, Mirtsos C, Sasaki T, Ruland J, Penninger J, Siderovski D, Mak T",
   ti:"Negative regulation of PKB/Akt-dependent cell survival by the tumor suppressor PTEN",
   jo:"Cell", vp:"95:29-39", doi:"10.1016/s0092-8674(00)81780-8"},
  {n:7,  y:1998, au:"Suzuki A, Pompa J, Stambolic V, Elia A, Sasaki T, Barrantes I, Ho A, Wakeham A, Itie A, Khoo W, Fukumoto M, Mak T",
   ti:"High cancer susceptibility and embryonic lethality associated with mutation of the PTEN tumor suppressor gene in mice",
   jo:"Curr Biol", vp:"8:1169-1178", doi:"10.1016/s0960-9822(07)00488-5"},
  {n:8,  y:1998, au:"Sasaki T, Maehama T, Yamamoto T, Takasuga S, Hoshino S, Nishina H, Hazeki O, Katada T",
   ti:"Activation of c-Jun N-terminal kinase (JNK) by lyso-phosphatidic acid in Swiss 3T3 fibroblasts",
   jo:"J Biochem", vp:"124:934-939", doi:"10.1093/oxfordjournals.jbchem.a022210"},
  {n:9,  y:1999, au:"Nishina H, Vaz C, Billia P, Nghiem M, Sasaki T, Pompa J, Furlonger K, Paige C, Hui C, Fischer K, Kishimoto H, Katada T, Woodgett J, Penninger J",
   ti:"Defective liver formation and liver cell apoptosis in mice lacking the stress signaling kinase SEK1/MKK4",
   jo:"Development", vp:"126:505-516", doi:"10.1242/dev.126.3.505"},
  {n:10, y:1999, au:"Hakem A, Sasaki T, Kozieradzki I, Penninger J",
   ti:"The cyclin-dependent kinase Cdk2 regulates thymocyte apoptosis",
   jo:"J Exp Med", vp:"189:957-967", doi:"10.1084/jem.189.6.957"},
  {n:11, y:1999, au:"Liu Q, Sasaki T, Kozieradzki I, Wakeham A, Itie A, Dumont D, Penninger J",
   ti:"SHIP is a negative regulator of growth factor receptor-mediated PKB/Akt activity and myeloid cell survival",
   jo:"Genes Dev", vp:"13:786-791", doi:"10.1101/gad.13.7.786"},
  {n:12, y:1999, au:"Lomaga M, Yeh W, Sarosi I, Duncan G, Furlonger C, Ho A, Morony S, Capparelli C, Van G, Kaufman S, van der Heiden A, Itie A, Wakeham A, Khoo W, Sasaki T, Cao Z, Penninger J, Paige C, Lacey D, Dunstan C, Boyle W, Goeddel D, Mak T",
   ti:"TRAF6 deficiency results in osteopetrosis and defective interleukin-1, CD40, and LPS signaling",
   jo:"Genes Dev", vp:"13:1015-1024", doi:"10.1101/gad.13.8.1015"},
  {n:13, y:1999, au:"Penninger J, Fischer K, Sasaki T, Kozieradzki I, Le J, Tedford K, Bachmaier K, Ohashi P, Bachmann M",
   ti:"The oncogene product Vav is a crucial regulator of primary cytotoxic T cell responses but has no apparent role in CD28-mediated co-stimulation",
   jo:"Eur J Immunol", vp:"29:1709-1718", doi:"10.1002/(SICI)1521-4141(199905)29:05<1709::AID-IMMU1709>3.0.CO;2-O"},
  {n:14, y:2000, au:"Bachmaier K, Krawczyk C, Kozieradzki I, Kong Y, Sasaki T, Olivera-dos-Santos A, Mariathasan S, Bouchard D, Wakeham A, Itie A, Le J, Ohashi P, Sarosi I, Nishina H, Lipkovitz S, Penninger J",
   ti:"Negative regulation of lymphocyte activation and autoimmunity by the molecular Cbl-b",
   jo:"Nature", vp:"403:211-216", doi:"10.1038/35003228"},
  {n:15, y:2000, au:"Sasaki T, Irie-Sasaki J, Jones R, Olivera-dos-Santos A, Stanford W, Bolon B, Wakeham A, Itie A, Bouchard D, Kozieradzki I, Joza N, Mak T, Ohashi P, Suzuki A, Penninger J",
   ti:"Function of PI3Kγ in thymocyte development, T cell activation, and neutrophil migration",
   jo:"Science", vp:"287:1040-1046", doi:"10.1126/science.287.5455.1040"},
  {n:16, y:2000, au:"Sasaki T, Irie-Sasaki J, Horie Y, Bachmaier K, Fata J, Li M, Suzuki A, Bouchard D, Ho A, Redston M, Gallinger S, Khokha R, Mak T, Hawkins P, Stephens L, Scherer S, Tsao M, Penninger J",
   ti:"Colorectal carcinomas in mice lacking the catalytic subunit of PI(3)Kγ",
   jo:"Nature", vp:"406:897-902", doi:"10.1038/35022585"},
  {n:17, y:2000, au:"Fata J, Kong Y, Li J, Sasaki T, Irie-Sasaki J, Moorehead R, Elliott R, Scully S, Voura E, Lacey D, Boyle W, Khokha R, Penninger J",
   ti:"The osteoclast differentiation factor osteoprotegerin-ligand is essential for mammary gland development",
   jo:"Cell", vp:"103:41-50", doi:"10.1016/s0092-8674(00)00103-3"},
  {n:18, y:2000, au:"Olivera-dos-Santos A, Matsumoto G, Snow B, Bai D, Houston F, Whishaw I, Mariathasan S, Sasaki T, Wakeham A, Ohashi P, Roder J, Barnes A, Siderovski D, Penninger J",
   ti:"Regulation of T cell activation, anxiety, and male aggression by RGS2",
   jo:"Proc Natl Acad Sci USA", vp:"97:12272-12277", doi:"10.1073/pnas.220414397"},
  {n:19, y:2000, au:"Boehmelt G, Wakeham A, Elia A, Sasaki T, Plyte S, Potter J, Yang Y, Tsang E, Ruland J, Iscove N, Dennis J, Mak T",
   ti:"Decreased UDP-GlcNAc levels abrogate proliferation control in EMeg32-deficient cells",
   jo:"EMBO J", vp:"19:5092-5104", doi:"10.1093/emboj/19.19.5092"},
  {n:20, y:2000, au:"Krawczyk C, Bachmaier K, Sasaki T, Jones R, Snapper S, Bouchard D, Kozieradzki I, Ohashi P, Alt F, Penninger J",
   ti:"Cbl-b is a negative regulator of receptor clustering and raft aggregation in T cells",
   jo:"Immunity", vp:"13:463-473", doi:"10.1016/s1074-7613(00)00046-7"},
  {n:21, y:2001, au:"Clement S, Krause U, Desmedt F, Tanti J, Behrends J, Pesesse X, Sasaki T, Penninger J, Doherty M, Malaisse W, Dumont J, Brustel Y, Erneurx C, Hue L, Schurmans S",
   ti:"The lipid phosphatase SHIP2 controls insulin sensitivity",
   jo:"Nature", vp:"409:92-97", doi:"10.1038/35051094"},
  {n:22, y:2001, au:"Irie-Sasaki J, Sasaki T, Matsumoto W, Opavski A, Cheng M, Welstead G, Griffiths E, Krawczyk C, Richardson C, Aitken K, Iscov N, Koretzky G, Johnson P, Liu P, Rothstein D, Penninger J",
   ti:"CD45 is a JAK phosphatase and negatively regulates cytokine receptor signaling",
   jo:"Nature", vp:"409:349-354", doi:"10.1038/35053086"},
  {n:23, y:2001, au:"Bony C, Roche S, Shuichi U, Sasaki T, Crackower M, Penninger J, Mano H, Puceat M",
   ti:"A specific role of phosphatidylinositol 3-kinase γ: regulation of autonomic Ca2+ oscillations in cardiac cells",
   jo:"J Cell Biol", vp:"152:717-727", doi:"10.1083/jcb.152.4.717"},
  {n:24, y:2001, au:"Joza N, Susin S, Daugas E, Stanford W, Cho S, Li C, Sasaki T, Elia A, Cheng M, Ravagnan L, Ferri K, Zamzami N, Wakeham A, Hakem R, Yoshida H, Kong Y, Mak T, Pflucker J, Kroemer G, Penninger J",
   ti:"Essential role of the mitochondrial apoptosis-inducing factor in programmed cell death",
   jo:"Nature", vp:"410:549-554", doi:"10.1038/35069004"},
  {n:25, y:2001, au:"Suzuki A, Yamaguchi M, Ohteki T, Sasaki T, Kaisho T, Kimura Y, Yoshida R, Wakeham A, Fukumoto M, Tsubata T, Ohashi P, Koyasu S, Penninger J, Nakano T, Mak T",
   ti:"T cell-specific loss of Pten leads to defects in central and peripheral tolerance",
   jo:"Immunity", vp:"14:523-534", doi:"10.1016/s1074-7613(01)00134-0"},
  {n:26, y:2001, au:"Wada T, Nakagawa K, Watanabe T, Nishitai G, Seo J, Kishimoto H, Kitagawa D, Sasaki T, Penninger J, Nishina H, Katada T",
   ti:"Impaired synergistic activation of stress-activated protein kinase SAPK/JNK in mouse embryonic stem cells lacking SEK1/MKK4",
   jo:"J Biol Chem", vp:"276:30892-30897", doi:"10.1074/jbc.M011780200"},
  {n:27, y:2001, au:"Sasaki T, Wada T, Kishimoto H, Irie-Sasaki J, Matsumoto G, Goto T, Yao Z, Wakeham A, Mak T, Suzuki A, Cho SK, Zuniga-Pflucker J, Oliveira-dos-Santos A, Katada T, Nishina H, Penninger J",
   ti:"The stress kinase MKK7 is a negative regulator of antigen receptor and growth factor receptor induced proliferation in hematopoietic cells",
   jo:"J Exp Med", vp:"194:757-768", doi:"10.1084/jem.194.6.757"},
  {n:28, y:2001, au:"Yum H, Arcaroli J, Kupfner J, Shenkar R, Penninger J, Sasaki T, Yang K, Park J, Abraham E",
   ti:"Involvement of Phosphoinositide 3-kinases in neutrophil activation and the development of acute lung injury",
   jo:"J Immunol", vp:"167:6601-6608", doi:"10.4049/jimmunol.167.11.6601"},
  {n:29, y:2002, au:"Krawczyk C, Olivera-dos-Santos A, Sasaki T, Griffiths E, Ohashi P, Snapper S, Alt F, Penninger J",
   ti:"Vav1 controls integrin clustering and MHC/peptide-specific cell adhesion to antigen-presenting cells",
   jo:"Immunity", vp:"16:331-343", doi:"10.1016/s1074-7613(02)00291-1"},
  {n:30, y:2002, au:"Yamazaki M, Miyazaki H, Watanabe H, Sasaki T, Maehama T, Frohman M, Kanaho Y",
   ti:"Phosphatidylinositol 4-phosphate 5-kinase is essential for ROCK-mediated neurite remodeling",
   jo:"J Biol Chem", vp:"277:17226-17230", doi:"10.1074/jbc.M109795200"},
  {n:31, y:2002, au:"Crackower M, Oudit G, Kozieradzki I, Sarao R, Sasaki T, Hirsch E, Suzuki A, Shioi T, Sasaki J, Sah R, Cheng H, Rybin V, Lembo G, Fratta L, Oliveira-dos-Santos A, Benovic J, Kahn R, Izumo S, Steinberg S, Wymann M, Backx P, Penninger J",
   ti:"Regulation of myocardial contractility and cell size by distinct PI3K-PTEN signaling pathway",
   jo:"Cell", vp:"110:737-749", doi:"10.1016/s0092-8674(02)00969-8"},
  {n:32, y:2002, au:"Ito N, Yokomizo T, Sasaki T, Kurosu H, Penninger J, Kanaho Y, Katada T, Hanaoka K, Shimizu T",
   ti:"Requirement of phosphatidylinositol 3-kinase activation and Ca2+ influx for leukotriene B4-induced enzyme release",
   jo:"J Biol Chem", vp:"277:44898-44904", doi:"10.1074/jbc.M208051200"},
  {n:33, y:2003, au:"Suzuki A, Itami S, Ohishi M, Hamada K, Inoue T, Komazawa N, Senoo H, Sasaki T, Takeda J, Manabe M, Mak T, Nakano T",
   ti:"Keratinocyte-specific Pten deficiency results in epidermal hyperplasia, accelerated hair follicle morphogenesis and tumor formation",
   jo:"Cancer Res", vp:"63:674-681", doi:""},
  {n:34, y:2003, au:"Nogami M, Yamazaki M, Watanabe H, Okabayashi Y, Kido Y, Kasuga M, Sasaki T, Maehama T, Kanaho Y",
   ti:"Requirement of autophosphorylated tyrosine 992 of EGF receptor and its docking protein phospholipase Cγ1 for membrane ruffle formation",
   jo:"FEBS Lett", vp:"536:71-76", doi:"10.1016/s0014-5793(03)00013-9"},
  {n:35, y:2003, au:"Suzuki A, Kaisho T, Ohishi M, Tsukio-Yamaguchi M, Tsubata T, Koni P, Sasaki T, Mak T, Nakano T",
   ti:"Critical roles of Pten in B cell homeostasis and immunoglobulin class switch recombination",
   jo:"J Exp Med", vp:"197:657-667", doi:"10.1084/jem.20021101"},
  {n:36, y:2003, au:"Kishimoto H, Nakagawa K, Watanabe T, Kitagawa D, Momose H, Seo J, Nishitai G, Shimizu N, Ohata S, Tanemura S, Asaka S, Goto T, Fukushi H, Yoshida H, Suzuki A, Sasaki T, Wada T, Penninger J, Nishina H, Katada T",
   ti:"Different properties of SEK1 and MKK7 in dual phosphorylation of stress-induced activated protein kinase SAPK/JNK in embryonic stem cells",
   jo:"J Biol Chem", vp:"278:16595-16601", doi:"10.1074/jbc.M213182200"},
  {n:37, y:2003, au:"Kim A, Sasaki T, Chao M",
   ti:"JNK interacting protein 1 promotes Akt1 activation",
   jo:"J Biol Chem", vp:"278:29830-29836", doi:"10.1074/jbc.M305349200"},
  {n:38, y:2003, au:"Woo M, Hakem R, Furlonger C, Hakem A, Duncan G, Sasaki T, Bouchard D, Lu L, Wu G, Paige C, Mak T",
   ti:"Caspase-3 regulates cell cycle in B cells: a consequence of substrate specificity",
   jo:"Nature Immunol", vp:"4:1016-1022", doi:"10.1038/ni976"},
  {n:39, y:2003, au:"Giuriato S, Pesesse X, Bodin S, Sasaki T, Viala C, Marion E, Penninger J, Schurmans S, Erneux C, Payrastre B",
   ti:"SH2 domain containing inositol 5-phosphatases 1 and 2 in blood platelets: interaction and respective role in the control of phosphatidylinositol 3,4,5-trisphosphate level",
   jo:"Biochem J", vp:"376:199-207", doi:"10.1042/BJ20030581"},
  {n:40, y:2003, au:"Oudit G, Crackower M, Eriksson U, Sarao R, Kozieradzki I, Sasaki T, Sasaki J, Gidrewicz D, Rybin V, Wada T, Steinberg S, Backx P, Penninger J",
   ti:"Phosphoinositide 3-kinase γ-deficient mice are protected from isoproterenol-induced heart failure",
   jo:"Circulation", vp:"108:2147-2152", doi:"10.1161/01.CIR.0000091403.62293.2B"},
  {n:41, y:2004, au:"Watanabe H, Yamazaki M, Miyazaki H, Arikawa C, Itoh K, Sasaki T, Maehama T, Frohman M, Kanaho Y",
   ti:"Phospholipase D2 functions as a downstream signaling molecule of MAP kinase pathway in L1-stimulated neurite outgrowth of cerebellar granule neurons",
   jo:"J Neurochem", vp:"89:142-151", doi:"10.1111/j.1471-4159.2004.02308.x"},
  {n:42, y:2004, au:"Wada T, Joza N, Cheng M, Sasaki T, Kozieradzki I, Bachmaier K, Katada T, Schreiber M, Wagner E, Nishina H, Penninger J",
   ti:"MKK7 couples stress signaling to G2/M cell cycle progression and cellular senescence",
   jo:"Nat Cell Biol", vp:"6:215-226", doi:"10.1038/ncb1098"},
  {n:43, y:2004, au:"Horie Y, Suzuki A, Kataoka E, Sasaki T, Hamada K, Sasaki J, Mizuno K, Hasegawa G, Kishimoto H, Iizuka M, Naito M, Enomoto K, Watanabe S, Mak T, Nakano T",
   ti:"Hepatocyte-specific Pten deficiency results in steatohepatitis and hepatocellular carcinomas",
   jo:"J Clin Invest", vp:"113:1774-1783", doi:"10.1172/JCI20513"},
  {n:44, y:2004, au:"Watanabe H, Yokozeki T, Yamazaki M, Miyazaki H, Sasaki T, Maehama T, Itoh K, Frohman M, Kanaho Y",
   ti:"Essential role for phospholipase D2 activation downstream of ERK MAP kinase in NGF-stimulated neurite outgrowth from PC12 cells",
   jo:"J Biol Chem", vp:"279:37870-37877", doi:"10.1074/jbc.M402610200"},
  {n:45, y:2004, au:"Reif K, Okkenhaug K, Sasaki T, Penninger J, Vanhaesebroeck B, Cyster J",
   ti:"Differential roles for phosphoinositide 3-kinases, p110γ and p110δ, in lymphocyte chemotaxis and homing",
   jo:"J Immunol", vp:"173:2236-2240", doi:"10.4049/jimmunol.173.4.2236"},
  {n:46, y:2005, au:"Sasaki J, Sasaki T, Yamazaki M, Matsuoka K, Taya C, Shitara H, Takasuga S, Nishio M, Mizuno K, Wada T, Miyazaki H, Watanabe H, Iizuka R, Kubo S, Murata S, Chiba T, Maehama T, Hamada K, Kishimoto H, Frohman M, Tanaka K, Penninger J, Yonekawa H, Suzuki A, Kanaho Y",
   ti:"Regulation of anaphylactic responses by phosphatidylinositol phosphate kinase type I α",
   jo:"J Exp Med", vp:"201:859-870", doi:"10.1084/jem.20041891"},
  {n:47, y:2005, au:"Hamada K, Sasaki T, Koni P, Natsui M, Kishimoto H, Sasaki J, Yajima N, Horie Y, Hasegawa G, Naito M, Miyazaki J, Suda T, Itoh H, Nakao K, Mak T, Nakano T, Suzuki A",
   ti:"The PTEN/PI3K pathway governs normal vascular development and tumor angiogenesis",
   jo:"Genes Dev", vp:"19:2054-2065", doi:"10.1101/gad.1308805"},
  {n:48, y:2006, au:"Sato W, Horie Y, Kataoka E, Ohshima S, Dohmen T, Iizuka M, Sasaki J, Sasaki T, Hamada K, Kishimoto H, Suzuki A, Watanabe S",
   ti:"Hepatic gene expression in hepatocyte-specific Pten deficient mice showing steatohepatitis without ethanol challenge",
   jo:"Hepatol Res", vp:"34:256-265", doi:"10.1016/j.hepres.2006.01.003"},
  {n:49, y:2006, au:"Yogo K, Mizutamari M, Mishima K, Takenouchi H, Ishida-Kitagawa N, Sasaki T, Takeya T",
   ti:"Src homology 2 (SH2)-containing 5'-inositol phosphatase localizes to podosomes, and the SH2 domain is implicated in the attenuation of bone resorption in osteoclasts",
   jo:"Endocrinology", vp:"147:3307-3317", doi:"10.1210/en.2005-1309"},
  {n:50, y:2006, au:"Zhao M, Song B, Pu J, Wada T, Reid B, Tai G, Wang F, Guo A, Walczysko P, Gu Y, Sasaki T, Suzuki A, Forrester J, Bourne H, Devreotes P, McCaig C, Penninger J",
   ti:"Electrical signals control wound healing through phosphatidylinositol-3-OH kinase-γ and PTEN",
   jo:"Nature", vp:"442:457-460", doi:"10.1038/nature04925"},
  {n:51, y:2006, au:"Suzuki T, Kanai Y, Hara T, Sasaki J, Sasaki T, Kohara M, Maehama T, Taya C, Shitara H, Yonekawa H, Frohman M, Yokozeki T, Kanaho Y",
   ti:"Crucial role of the small GTPase ARF6 in hepatic cord formation during liver development",
   jo:"Mol Cell Biol", vp:"26:6149-6156", doi:"10.1128/MCB.00298-06"},
  {n:52, y:2006, au:"Tsuruta H, Kishimoto H, Sasaki T, Natsui M, Shibata Y, Tsuchiya N, Horie Y, Hamada K, Yajima N, Enomoto K, Gordon J, Mak T, Nakano T, Habuchi T, Suzuki A",
   ti:"Hyperplasia and carcinomas in Pten-deficient mice and reduced PTEN protein in human bladder cancer patients",
   jo:"Cancer Res", vp:"66:8389-8396", doi:"10.1158/0008-5472.CAN-05-4627"},
  {n:53, y:2006, au:"Kunisaki Y, Nishikimi A, Tanaka Y, Takii R, Noda M, Inayoshi A, Watanabe K, Sasazuki T, Sasaki T, Fukui Y",
   ti:"DOCK2 is a Rac activator that regulates motility and polarity during neutrophil chemotaxis",
   jo:"J Cell Biol", vp:"174:647-652", doi:"10.1083/jcb.200602142"},
  {n:54, y:2007, au:"Nishio M, Watanabe K, Sasaki J, Taya C, Takasuga S, Iizuka R, Balla T, Yamazaki M, Watanabe H, Itoh R, Kuroda S, Horie Y, Förster I, Mak T, Yonekawa H, Penninger J, Kanaho Y, Suzuki A, Sasaki T",
   ti:"Control of cell polarity and motility by the PI(3,4,5)P<sub>3</sub> phosphatase SHIP1",
   jo:"Nat Cell Biol", vp:"9:36-44", doi:"10.1038/ncb1515"},
  {n:55, y:2007, au:"Ferguson J, Milne L, Kulkarni S, Sasaki T, Walker S, Andrews S, Crabbe T, Finan P, Jones G, Jackson S, Camps M, Rommel C, Wymann M, Hirsch E, Hawkins P, Stephens L",
   ti:"PI(3)Kγ has an important context-dependent role in chemokinesis",
   jo:"Nat Cell Biol", vp:"9:86-91", doi:"10.1038/ncb1517"},
  {n:56, y:2007, au:"Kishimoto H, Ohteki T, Yajima N, Kawahara K, Natsui M, Kawarasaki S, Hamada K, Horie Y, Kubo Y, Arase S, Taniguchi M, Vanhaesebroeck B, Mak T, Nakano T, Koyasu S, Sasaki T, Suzuki A",
   ti:"The Pten/PI3K pathway governs the homeostasis of Vα14 iNKT cells",
   jo:"Blood", vp:"109:3316-3324", doi:"10.1182/blood-2006-07-038059"},
  {n:57, y:2007, au:"Furutani Y, Matsuno H, Kawasaki M, Sasaki T, Mori K, Yoshihara Y",
   ti:"Interaction between telencepalin and ERM family proteins mediates dendritic filopodia formation",
   jo:"J Neurosci", vp:"27:8866-8876", doi:"10.1523/JNEUROSCI.1047-07.2007"},
  {n:58, y:2007, au:"Yanagi S, Kishimoto H, Kawahara K, Sasaki T, Sasaki M, Nishio M, Yajima N, Hamada K, Horie Y, Kubo H, Mak T, Nakano T, Nakazato M, Suzuki A",
   ti:"Pten controls lung morphogenesis, bronchioalveolar stem cells, and onset of lung adenocarcinomas",
   jo:"J Clin Invest", vp:"117:2929-2940", doi:"10.1172/JCI31854"},
  {n:59, y:2007, au:"Horan K, Watanabe K, Kong A, Bailey C, Rasko J, Sasaki T, Mitchell C",
   ti:"Regulation of FcγR-stimulated phagocytosis by the 72 kDa inositol polyphosphate 5-phosphatase",
   jo:"Blood", vp:"110:4480-4491", doi:"10.1182/blood-2007-02-073874"},
  {n:60, y:2008, au:"Kuwana H, Terada Y, Kobayashi T, Okado T, Penninger J, Sasaki J, Sasaki T, Sasaki S",
   ti:"The phosphoinositide-3 kinase-γ–Akt pathway mediates renal tubular injury in cisplatin nephrotoxicity",
   jo:"Kidney Int", vp:"73:430-445", doi:"10.1038/sj.ki.5002702"},
  {n:61, y:2008, au:"Tsukamoto K, Hazeki K, Hoshi M, Nigorikawa K, Inoue N, Sasaki T, Hazeki O",
   ti:"Critical roles of the p110β subtype of phosphoinositide 3-kinase in lipopolysaccharide-induced Akt activation and negative regulation of nitrite production in RAW 264.7 cells",
   jo:"J Immunol", vp:"180:2054-2061", doi:"10.4049/jimmunol.180.4.2054"},
  {n:62, y:2008, au:"Wang Y, Litvinov R, Xinsheng D, Bach T, Lian L, Petrich B, Monkley S, Critcheley D, Sasaki T, Birnbaum M, Weisel J, Hartwig J, Abrams C",
   ti:"Loss of PIP5KIγ, unlike other PIP5KI isoforms, impairs the integrity of the membrane cytoskeleton in murine megakaryocytes",
   jo:"J Clin Invest", vp:"118:812-819", doi:"10.1172/JCI34239"},
  {n:63, y:2008, au:"Garcon F, Patton D, Emery J, Hirsch E, Rottapel R, Sasaki T, Okkenhaug K",
   ti:"CD28 provides T cell costimulation and enhances PI3K activity at the immune synapse independently of its capacity to interact with the p85/p110 heterodimer",
   jo:"Blood", vp:"111:1464-1471", doi:"10.1182/blood-2007-08-108050"},
  {n:64, y:2008, au:"Kuroda S, Nishio M, Sasaki T, Horie Y, Kawahara K, Sasaki M, Natsui M, Matozaki T, Tezuka H, Ohteki T, Forster I, Mak T, Nakano T, Suzuki A",
   ti:"Effective clearance of intracellular Leishmania major in vivo requires Pten in macrophages",
   jo:"Eur J Immunol", vp:"38:1131-1140", doi:"10.1002/eji.200737302"},
  {n:65, y:2008, au:"Inoue-Narita T, Hamada K, Sasaki T, Hatakeyama S, Fujita S, Kawahara K, Sasaki M, Kishimoto H, Eguchi S, Kojima I, Beermann F, Kimura T, Osawa M, Itami S, Mak T, Nakano T, Manabe M, Suzuki A",
   ti:"Pten deficiency in melanocytes results in resistance to hair graying and susceptibility to carcinogen-induced melanomagenesis",
   jo:"Cancer Res", vp:"68:5760-5768", doi:"10.1158/0008-5472.CAN-08-0889"},
  {n:66, y:2008, au:"Nakasaki M, Yoshioka K, Miyamoto Y, Sasaki T, Yoshikawa H, Itoh K",
   ti:"IGF-I secreted by osteoblasts acts as a potent chemotactic factor for osteoblast",
   jo:"Bone", vp:"43:869-879", doi:"10.1016/j.bone.2008.07.241"},
  {n:67, y:2008, au:"Iwasaki H, Murata Y, Kim Y, Hossain M, Worby C, Dixon J, McCormack T, Sasaki T, Okamura Y",
   ti:"A voltage-sensing phosphatase, Ci-VSP, which shares sequence identity with PTEN dephosphorylates phosphatidylinositol 4,5-bisphosphate",
   jo:"Proc Natl Acad Sci USA", vp:"105:7970-7975", doi:"10.1073/pnas.0803936105"},
  {n:68, y:2008, au:"Wang Y, Chen X, Lian L, Tang T, Stalker T, Sasaki T, Brass L, Choi J, Hartwig J, Abrams C",
   ti:"Loss of PIP5KIβ demonstrates that PIP5KI isoform-specific PIP2 synthesis is required for IP3 formation",
   jo:"Proc Natl Acad Sci USA", vp:"105:14064-14069", doi:"10.1073/pnas.0804139105"},
  {n:69, y:2008, au:"Hebiguchi M, Hirokawa M, Guo YM, Saito K, Wakui H, Komatsuda A, Fujishima N, Takahashi N, Sasaki T, Nunomura W, Takakuwa Y, Sawada K",
   ti:"Dynamics of human erythroblast enucleation",
   jo:"Int J Hematol", vp:"88:498-507", doi:"10.1007/s12185-008-0200-6"},
  {n:70, y:2009, au:"Ishii H, Horie Y, Ohshima S, Anezaki Y, Kinoshita N, Dohmen T, Kataoka E, Sato W, Goto T, Sasaki J, Sasaki T, Watanabe S, Suzuki A, Ohnishi H",
   ti:"Eicosapentaenoic acid ameliorates steatohepatitis and hepatocellular carcinoma in hepatocyte-specific Pten-deficient mice",
   jo:"J Hepatol", vp:"50:562-571", doi:"10.1016/j.jhep.2008.10.031"},
  {n:71, y:2009, au:"Takeda M, Ito W, Tanabe M, Ueki S, Kato H, Kihara J, Tanigai T, Chiba T, Yamaguchi K, Kayaba H, Imai Y, Okuyama K, Ohno I, Sasaki T, Chihara J",
   ti:"Allergic airway hyperresponsiveness, inflammation, and remodeling do not develop in phosphoinositide 3-kinase γ-deficient mice",
   jo:"J Allergy Clin Immunol", vp:"123:805-812", doi:"10.1016/j.jaci.2008.11.047"},
  {n:72, y:2009, au:"Mogi C, Tobo M, Tomura H, Murata N, He XD, Sato K, Kimura T, Ishizuka T, Sasaki T, Sato T, Kihara Y, Ishii S, Harada A, Okajima F",
   ti:"Involvement of proton-sensing TDAG8 in extracellular acidification-induced inhibition of proinflammatory cytokine production in peritoneal macrophages",
   jo:"J Immunol", vp:"182:3243-3251", doi:"10.4049/jimmunol.0803466"},
  {n:73, y:2009, au:"Anezaki Y, Ohshima S, Ishii H, Kinoshita N, Dohmen T, Kataoka E, Sato W, Iizuka M, Goto T, Sasaki J, Sasaki T, Suzuki A, Ohnishi H, Horie Y",
   ti:"Sex difference in the liver of hepatocyte-specific Pten-deficient mice: a model of nonalcoholic steatohepatitis",
   jo:"Hepatol Res", vp:"39:609-618", doi:"10.1111/j.1872-034X.2009.00494.x"},
  {n:74, y:2009, au:"Nishikimi A, Fukuhara H, Su W, Hongu T, Takasuga S, Mihara H, Cao Q, Sanematsu F, Kanai M, Hasegawa H, Tanaka Y, Shibasaki M, Kanaho Y, Sasaki T, Frohman MA, Fukui Y",
   ti:"Sequential regulation of DOCK2 dynamics by two phospholipids during neutrophil chemotaxis",
   jo:"Science", vp:"324:384-387", doi:"10.1126/science.1170179"},
  {n:75, y:2010, au:"Zhang H, He J, Kutateladze TG, Sakai T, Sasaki T, Markadieu N, Erneux C, Prestwich GD",
   ti:"5-Stabilized phosphatidylinositol 3,4,5-trisphosphate analogues bind Grp1 PH, inhibit phosphoinositide phosphatases, and block neutrophil migration",
   jo:"Chembiochem", vp:"11:388-395", doi:"10.1002/cbic.200900545"},
  {n:76, y:2010, au:"Sasaki J, Kofuji S, Itoh R, Momiyama T, Takayama K, Murakami H, Chida S, Tsuya Y, Takasuga S, Eguchi S, Asanuma K, Horie Y, Miura K, Davies E, Mitchell C, Yamazaki M, Hirai H, Takenawa T, Suzuki A, Sasaki T",
   ti:"The PtdIns(3,4)P<sub>2</sub>-phosphatase INPP4A is a suppressor of excitotoxic neuronal death",
   jo:"Nature", vp:"465:497-501", doi:"10.1038/nature09023"},
  {n:77, y:2010, au:"Volpicelli-Daley LA, Lucast L, Gong LW, Liu L, Sasaki J, Sasaki T, Abrams CS, Kanaho Y, De Camilli P",
   ti:"Phosphatidylinositol-4-phosphate 5-kinases and phosphatidylinositol 4,5-bisphosphate synthesis in the brain",
   jo:"J Biol Chem", vp:"285:28708-28714", doi:"10.1074/jbc.M110.132191"},
  {n:78, y:2011, au:"Kobayashi N, Ueki K, Okazaki Y, Iwane A, Kubota N, Ohsugi M, Awazawa M, Kobayashi M, Sasako T, Kaneko K, Suzuki M, Nishikawa Y, Hara K, Yoshimura K, Koshima I, Goyama S, Murakami K, Sasaki J, Nagai R, Kurokawa M, Sasaki T, Kadowaki T",
   ti:"Blockade of class IB phosphoinositide-3 kinase ameliorates obesity-induced inflammation and insulin resistance",
   jo:"Proc Natl Acad Sci USA", vp:"108:5753-5758", doi:"10.1073/pnas.1016430108"},
  {n:79, y:2011, au:"Fujioka Y, Tsuda M, Hattori T, Sasaki J, Sasaki T, Miyazaki T, Ohba Y",
   ti:"The Ras-PI3K signaling pathway is involved in clathrin-independent endocytosis and the internalization of influenza viruses",
   jo:"PLoS One", vp:"6:e16324", doi:"10.1371/journal.pone.0016324"},
  {n:80, y:2011, au:"Kinoshita N, Horie Y, Ohshima S, Hirai Y, Dohmen T, Jin M, Matsuhashi T, Sasaki J, Sasaki T, Iizuka M, Ohnishi H",
   ti:"Epimorphin protects hepatocytes from oxidative stress by inhibiting mitochondrial injury",
   jo:"J Gastroenterol Hepatol", vp:"26:201-206", doi:"10.1111/j.1440-1746.2010.06327.x"},
  {n:81, y:2011, au:"Hazeki K, Kametani Y, Murakami H, Uehara M, Ishikawa Y, Nigorikawa K, Takasuga S, Sasaki T, Seya T, Matsumoto M, Hazeki O",
   ti:"Phosphoinositide 3-kinase γ controls the intracellular localization of CpG to limit DNA-PKcs-dependent IL-10 production in macrophages",
   jo:"PLoS One", vp:"6:e26836", doi:"10.1371/journal.pone.0026836"},
  {n:82, y:2011, au:"Sasaki M, Kawahara K, Nishio M, Mimori K, Kogo R, Hamada K, Itoh B, Wang J, Komatsu Y, Yang YR, Hikasa H, Horie Y, Yamashita T, Kamijo T, Zhang Y, Zhu Y, Prives C, Nakano T, Mak TW, Sasaki T, Maehama T, Mori M, Suzuki A",
   ti:"Regulation of the MDM2-P53 pathway and tumor growth by PICT1 via nucleolar RPL11",
   jo:"Nat Med", vp:"17:944-951", doi:"10.1038/nm.2392"},
  {n:83, y:2012, au:"Imae R, Inoue T, Nakasaki Y, Uchida Y, Ohba Y, Kono N, Nakanishi H, Sasaki T, Mitani S, Arai H",
   ti:"LYCAT, a homologue of C. elegans acl-8, acl-9, and acl-10, determines the fatty acid composition of phosphatidylinositol in mice",
   jo:"J Lipid Res", vp:"53:335-347", doi:"10.1194/jlr.M018655"},
  {n:84, y:2012, au:"Kurokawa T, Takasuga S, Sakata S, Yamaguchi S, Horie S, Homma KJ, Sasaki T, Okamura Y",
   ti:"3' Phosphatase activity toward phosphatidylinositol 3,4-bisphosphate [PI(3,4)P<sub>2</sub>] by voltage-sensing phosphatase (VSP)",
   jo:"Proc Natl Acad Sci USA", vp:"109:10089-10094", doi:"10.1073/pnas.1203799109"},
  {n:85, y:2012, au:"Kawamura N, Sun-Wada GH, Aoyama M, Harada A, Takasuga S, Sasaki T, Wada Y",
   ti:"Delivery of endosomes to lysosomes via microautophagy in the visceral endoderm of mouse embryos",
   jo:"Nat Commun", vp:"3:1071", doi:"10.1038/ncomms2069"},
  {n:86, y:2012, au:"Neely G, Rao S, Costigan M, Mair N, Racz I, Milinkeviciute G, Meixner A, Nayanala S, Griffin S, Belfer I, Dai F, Smith S, Diatchenko L, Marengo S, Haubner J, Novatchkova M, Gibson D, Maixner W, Pospisilik A, Hirsch E, Whishaw Q, Zimmer A, Gupta V, Sasaki J, Kanaho Y, Sasaki T, Kress M, Woolf J, Penninger J",
   ti:"Construction of a global pain systems network highlights phospholipid signaling as a regulator of heat nociception",
   jo:"PLoS Genet", vp:"8:e1003071", doi:"10.1371/journal.pgen.1003071"},
  {n:87, y:2012, au:"Nishio M, Hamada K, Kawahara K, Sasaki M, Noguchi F, Chiba S, Mizuno K, Suzuki SO, Dong Y, Tokuda M, Morikawa T, Hikasa H, Eggenschwiler J, Yabuta N, Nojima H, Nakagawa K, Hata Y, Nishina H, Mimori K, Mori M, Sasaki T, Mak TW, Nakano T, Itami S, Suzuki A",
   ti:"Cancer susceptibility and embryonic lethality in Mob1a/1b double-mutant mice",
   jo:"J Clin Invest", vp:"122:4505-4518", doi:"10.1172/JCI63735"},
  {n:88, y:2012, au:"Lee HC, Inoue T, Sasaki J, Kubo T, Matsuda S, Nakasaki Y, Hattori M, Tanaka F, Udagawa O, Kono N, Itoh T, Ogiso H, Taguchi R, Arita M, Sasaki T, Arai H",
   ti:"LPIAT1 regulates arachidonic acid content in phosphatidylinositol and is required for cortical lamination in mice",
   jo:"Mol Biol Cell", vp:"23:4689-4700", doi:"10.1091/mbc.E12-09-0673"},
  {n:89, y:2012, au:"Shinohara M, Nakamura M, Masuda H, Hirose J, Kadono Y, Iwasawa M, Nagase Y, Ueki K, Kadowaki T, Sasaki T, Kato S, Nakamura H, Tanaka S, Takayanagi H",
   ti:"Class IA phosphatidylinositol 3-kinase regulates osteoclastic bone resorption through Akt-mediated vesicle transport",
   jo:"J Bone Miner Res", vp:"27:2464-2475", doi:"10.1002/jbmr.1703"},
  {n:90, y:2012, au:"Yoshioka K, Yoshida K, Cui H, Wakayama T, Takuwa N, Okamoto Y, Du W, Qi X, Asanuma K, Sugihara K, Aki S, Miyazawa H, Biswas K, Nagakura C, Ueno M, Iseki S, Schwartz R, Okamoto H, Sasaki T, Matsui O, Asano M, Adams R, Takakura N, Takuwa Y",
   ti:"Essential role of endothelial class II PI3K-C2α in angiogenesis and vascular barrier function",
   jo:"Nat Med", vp:"18:1560-1569", doi:"10.1038/nm.2928"},
  {n:91, y:2012, au:"Biswas K, Yoshioka K, Asanuma K, Okamoto Y, Takuwa N, Sasaki T, Takuwa Y",
   ti:"Essential role of class II PI3K-C2α in sphingosine-1-phosphate receptor-1 mediated signaling and migration in endothelial cells",
   jo:"J Biol Chem", vp:"288:2325-2339", doi:"10.1074/jbc.M112.409656"},
  {n:92, y:2013, au:"Ichikawa A, Kuba K, Morita M, Chida S, Tezuka H, Hara H, Sasaki T, Ohteki T, Ranieri VM, Dos Santos CC, Kawaoka Y, Akira S, Luster AD, Lu B, Penninger JM, Uhlig S, Slutsky AS, Imai Y",
   ti:"CXCL10-CXCR3 enhances the development of neutrophil-mediated fulminant lung injury of viral and non-viral origin",
   jo:"Am J Respir Crit Care Med", vp:"187:65-77", doi:"10.1164/rccm.201203-0508OC"},
  {n:93, y:2013, au:"Huang M, Narita S, Inoue T, Tsuchiya N, Satoh S, Nanjo H, Sasaki T, Habuchi T",
   ti:"Diet-induced macrophage inhibitory cytokine 1 promotes prostate cancer progression",
   jo:"Endocr Relat Cancer", vp:"21:39-50", doi:"10.1530/ERC-13-0227"},
  {n:94, y:2013, au:"Morishita H, Eguchi S, Kimura H, Sasaki J, Sakamaki Y, Robinson ML, Sasaki T, Mizushima N",
   ti:"Deletion of autophagy-related 5 (Atg5) and Pik3c3 genes in the lens causes cataract independent of programmed organelle degradation",
   jo:"J Biol Chem", vp:"288:11436-11447", doi:"10.1074/jbc.M112.437103"},
  {n:95, y:2013, au:"Takasuga S, Horie Y, Sasaki J, Sun-Wada GH, Kawamura N, Iizuka R, Mizuno K, Eguchi S, Kofuji S, Kimura H, Yamazaki M, Horie C, Odanaga E, Sato Y, Chida S, Kontani K, Harada A, Katada T, Suzuki A, Wada Y, Ohnishi H, Sasaki T",
   ti:"Critical roles of type III phosphatidylinositol phosphate kinase in murine embryonic visceral endoderm and adult intestine",
   jo:"Proc Natl Acad Sci USA", vp:"110:1726-1731", doi:"10.1073/pnas.1213212110"},
  {n:96, y:2013, au:"Fujioka Y, Tsuda M, Nando A, Hattori T, Sasaki J, Sasaki T, Miyazaki T, Ohba Y",
   ti:"A Ca2+-dependent signaling circuit regulates influenza A virus internalization and infection",
   jo:"Nat Commun", vp:"4:2763", doi:"10.1038/ncomms2763"},
  {n:97, y:2014, au:"Ayukawa T, Akiyama M, Mummery-Widmer JL, Stoeger T, Sasaki J, Knoblich JA, Senoo H, Sasaki T, Yamazaki M",
   ti:"Dachsous-dependent asymmetric localization of Spiny-Legs determines planar cell polarity orientation in Drosophila",
   jo:"Cell Rep", vp:"8:610-621", doi:"10.1016/j.celrep.2014.06.009"},
  {n:98, y:2015, au:"Ip LR, Poulogiannis G, Viciano FC, Sasaki J, Kofuji S, Spanswick VJ, Hochhauser D, Hartley JA, Sasaki T, Gewinner CA",
   ti:"Loss of INPP4B causes a DNA repair defect through loss of BRCA1, ATM and ATR and can be targeted with PARP inhibitor treatment",
   jo:"Oncotarget", vp:"6:10548-10562", doi:"10.18632/oncotarget.3307"},
  {n:99, y:2015, au:"Chew CL, Lunardi A, Gulluni F, Ruan DT, Chen M, Salmena L, Nishino M, Papa A, Ng C, Fung J, Clohessy JG, Sasaki J, Sasaki T, Bronson RT, Hirsch E, Pandolfi PP",
   ti:"In vivo role of INPP4B in tumor and metastasis suppression through regulation of PI3K/AKT signaling at endosomes",
   jo:"Cancer Discov", vp:"5:740-751", doi:"10.1158/2159-8290.CD-14-1347"},
  {n:100, y:2015, au:"Kofuji S, Kimura H, Nakanishi H, Nanjo H, Takasuga S, Liu H, Eguchi S, Nakamura R, Itoh R, Ueno N, Asanuma K, Huang M, Koizumi A, Habuchi T, Yamazaki M, Suzuki A, Sasaki J, Sasaki T",
   ti:"INPP4B is a PtdIns(3,4,5)P<sub>3</sub> phosphatase that can act as a tumor suppressor",
   jo:"Cancer Discov", vp:"5:730-739", doi:"10.1158/2159-8290.CD-14-1329"},
  {n:101, y:2015, au:"Nigorikawa K, Hazeki K, Sasaki J, Omori Y, Miyake M, Morioka S, Guo Y, Sasaki T, Hazeki O",
   ti:"Inositol polyphosphate-4-phosphatase type I negatively regulates phagocytosis via dephosphorylation of phagosomal PtdIns(3,4)P<sub>2</sub>",
   jo:"PLoS One", vp:"10:e0142091", doi:"10.1371/journal.pone.0142091"},
  {n:102, y:2015, au:"Hammond GR, Takasuga S, Sasaki T, Balla T",
   ti:"The ML1Nx2 phosphatidylinositol 3,5-bisphosphate probe shows poor selectivity in cells",
   jo:"PLoS One", vp:"10:e0139957", doi:"10.1371/journal.pone.0139957"},
  {n:103, y:2016, au:"Norton L, Lindsay Y, Deladeriere A, Chessa T, Guillou H, Suire S, Lucocq J, Walker S, Andrews S, Segonds-Pichon A, Rausch O, Finan P, Sasaki T, Du CJ, Bretschneider T, Ferguson GJ, Hawkins PT, Stephens L",
   ti:"Localizing the lipid products of PI3Kγ in neutrophils",
   jo:"Adv Biol Regul", vp:"60:36-45", doi:"10.1016/j.jbior.2015.10.005"},
  {n:104, y:2016, au:"Nishio M, Sugimachi K, Goto H, Wang J, Morikawa T, Miyachi Y, Takano Y, Hikasa H, Itoh T, Suzuki SO, Kurihara H, Aishima S, Leask A, Sasaki T, Nakano T, Nishina H, Nishikawa Y, Sekido Y, Nakao K, Shin-Ya K, Mimori K, Suzuki A",
   ti:"Dysregulated YAP1/TAZ and TGF-β signaling mediate hepatocarcinogenesis in Mob1a/1b-deficient mice",
   jo:"Proc Natl Acad Sci USA", vp:"113:E71-80", doi:"10.1073/pnas.1517188113"},
  {n:105, y:2016, au:"Huang M, Koizumi A, Narita S, Inoue T, Tsuchiya N, Nakanishi H, Numakura K, Tsuruta H, Saito M, Satoh S, Nanjo H, Sasaki T, Habuchi T",
   ti:"Diet-induced alteration of fatty acid synthase in prostate cancer progression",
   jo:"Oncogenesis", vp:"5:e195", doi:"10.1038/oncsis.2015.42"},
  {n:106, y:2016, au:"Morioka S, Nigorikawa K, Sasaki J, Hazeki K, Kasuu Y, Sasaki T, Hazeki O",
   ti:"Myeloid cell-specific inositol polyphosphate-4-phosphatase type I knockout mice impair bacteria clearance in a murine peritonitis model",
   jo:"Innate Immun", vp:"22:444-451", doi:"10.1177/1753425916652714"},
  {n:107, y:2017, au:"Kimura H, Eguchi S, Sasaki J, Kuba K, Nakanishi H, Takasuga S, Yamazaki M, Goto A, Watanabe H, Itoh H, Imai Y, Suzuki A, Mizushima N, Sasaki T",
   ti:"Vps34 regulates myofibril proteostasis to prevent hypertrophic cardiomyopathy",
   jo:"JCI Insight", vp:"2:e89462", doi:"10.1172/jci.insight.89462"},
  {n:108, y:2017, au:"Matsumoto J, Nakanishi H, Kunii Y, Sugiura Y, Yuki D, Wada A, Hino M, Niwa SI, Kondo T, Waki M, Hayasaka T, Masaki N, Akatsu H, Hashizume Y, Yamamoto S, Sato S, Sasaki T, Setou M, Yabe H",
   ti:"Decreased 16:0/20:4-phosphatidylinositol level in the post-mortem prefrontal cortex of elderly patients with schizophrenia",
   jo:"Sci Rep", vp:"7:45050", doi:"10.1038/srep45050"},
  {n:109, y:2017, au:"Otsubo K, Goto H, Nishio M, Kawamura K, Yanagi S, Nishie W, Sasaki T, Maehama T, Nishina H, Mimori K, Nakano T, Shimizu H, Mak TW, Nakao K, Nakanishi Y, Suzuki A",
   ti:"MOB1-YAP1/TAZ-NKX2.1 axis controls bronchioalveolar cell differentiation, adhesion and tumour formation",
   jo:"Oncogene", vp:"36:4201-4211", doi:"10.1038/onc.2017.58"},
  {n:110, y:2017, au:"Shindou H, Koso H, Sasaki J, Nakanishi H, Sagara H, Nakagawa KM, Takahashi Y, Hishikawa D, Iizuka-Hishikawa Y, Tokumasu F, Noguchi H, Watanabe S, Sasaki T, Shimizu T",
   ti:"Docosahexaenoic acid preserves visual function by maintaining correct disc morphology in retinal photoreceptor cells",
   jo:"J Biol Chem", vp:"292:12054-12064", doi:"10.1074/jbc.M117.790568"},
  {n:111, y:2017, au:"Iizuka-Hishikawa Y, Hishikawa D, Sasaki J, Takubo K, Goto M, Nagata K, Nakanishi H, Shindou H, Okamura T, Ito C, Toshimori K, Sasaki T, Shimizu T",
   ti:"Lysophosphatidic acid acyltransferase 3 tunes the membrane status of germ cells by incorporating docosahexaenoic acid during spermatogenesis",
   jo:"J Biol Chem", vp:"292:12065-12076", doi:"10.1074/jbc.M117.791277"},
  {n:112, y:2017, au:"Kimura H, Matsuyama Y, Araki S, Koizumi A, Kariya Y, Takasuga S, Eguchi S, Nakanishi H, Sasaki J, Sasaki T",
   ti:"The effect and possible clinical efficacy of in vivo inhibition of neutrophil extracellular traps by blockade of PI3K-gamma on the pathogenesis of microscopic polyangiitis",
   jo:"Mod Rheumatol", vp:"28:530-541", doi:"10.1080/14397595.2017.1367116"},
  {n:113, y:2017, au:"Malek M, Kielkowska A, Chessa T, Anderson K, Barneda D, Pir P, Nakanishi H, Eguchi S, Koizumi A, Sasaki J, Juvin V, Kiselev V, Niewczas I, Gray A, Valayer A, Spensberger D, Imbert M, Felisbino S, Habuchi T, Beinke S, Cosulich S, Le Novere N, Sasaki T, Clark J, Hawkins P, Stephens L",
   ti:"PTEN regulates PI(3,4)P<sub>2</sub> signaling downstream of class I PI3K",
   jo:"Mol Cell", vp:"68:566-580", doi:"10.1016/j.molcel.2017.09.024"},
  {n:114, y:2018, au:"Morioka S, Nigorikawa K, Okada E, Tanaka Y, Kasuu Y, Yamada M, Kofuji S, Takasuga S, Nakanishi H, Sasaki T, Hazeki K",
   ti:"TMEM55a localizes to macrophage phagosomes to downregulate phagocytosis",
   jo:"J Cell Sci", vp:"131:jcs213272", doi:"10.1242/jcs.213272"},
  {n:115, y:2018, au:"Liggins MC, Flesher JL, Jahid S, Vasudeva P, Eby V, Takasuga S, Sasaki J, Sasaki T, Boissy RE, Ganesan AK",
   ti:"PIKfyve regulates melanosome biogenesis",
   jo:"PLoS Genet", vp:"14:e1007290", doi:"10.1371/journal.pgen.1007290"},
  {n:116, y:2018, au:"Makinoshima H, Umemura S, Suzuki A, Nakanishi H, Maruyama A, Udagawa H, Mimaki S, Matsumoto S, Niho S, Ishii G, Tsuboi M, Ochiai A, Esumi H, Sasaki T, Goto K, Tsuchihara K",
   ti:"Metabolic determinants of sensitivity to phosphatidylinositol 3-kinase pathway inhibitor in small-cell lung carcinoma",
   jo:"Cancer Res", vp:"78:2179-2190", doi:"10.1158/0008-5472.CAN-17-2109"},
  {n:117, y:2019, au:"Nishio M, Miyachi Y, Otani J, Tane S, Omori H, Ueda F, Togashi H, Sasaki T, Mak TW, Nakao K, Fujita Y, Nishina H, Maehama T, Suzuki A",
   ti:"Hippo pathway controls cell adhesion and context-dependent cell competition to influence skin engraftment efficiency",
   jo:"FASEB J", vp:"33:5548-5560", doi:"10.1096/fj.201802005R"},
  {n:118, y:2019, au:"Takemasu S, Ito M, Morioka S, Nigorikawa K, Kofuji S, Takasuga S, Eguchi S, Nakanishi H, Matsuoka I, Sasaki J, Sasaki T, Hazeki K",
   ti:"Lysophosphatidylinositol-acyltransferase-1 is involved in cytosolic Ca2+ oscillations in macrophages",
   jo:"Genes Cells", vp:"24:366-376", doi:"10.1111/gtc.12681"},
  {n:119, y:2019, au:"Fujioka Y, Satoh AO, Horiuchi K, Fujioka M, Tsutsumi K, Sasaki J, Nepal P, Kashiwagi S, Paudel S, Nishide S, Nanbo A, Sasaki T, Ohba Y",
   ti:"A peptide derived from phosphoinositide 3-kinase inhibits endocytosis and influenza virus infection",
   jo:"Cell Struct Funct", vp:"44:61-74", doi:"10.1247/csf.19001"},
  {n:120, y:2019, au:"McCormick B, Craig HE, Chu JY, Carlin LM, Canel M, Wollweber F, Toivakka M, Michael M, Astier AL, Norton L, Lilja J, Felton JM, Sasaki T, Ivaska J, Hers I, Dransfield I, Rossi AG, Vermeren S",
   ti:"A negative feedback loop regulates integrin inactivation and promotes neutrophil recruitment to inflammatory sites",
   jo:"J Immunol", vp:"203:1579-1588", doi:"10.4049/jimmunol.1900443"},
  {n:121, y:2019, au:"Koizumi A, Narita S, Nakanishi H, Ishikawa M, Eguchi S, Kimura H, Takasuga S, Huang M, Inoue T, Sasaki J, Yoshioka T, Habuchi T, Sasaki T",
   ti:"Increased fatty acyl saturation of phosphatidylinositol phosphates in prostate cancer progression",
   jo:"Sci Rep", vp:"9:13257", doi:"10.1038/s41598-019-49744-3"},
  {n:122, y:2019, au:"Kawai T, Miyata H, Nakanishi H, Sakata S, Morioka S, Sasaki J, Watanabe M, Sakimura K, Fujimoto T, Sasaki T, Ikawa M, Okamura Y",
   ti:"Polarized PtdIns(4,5)P<sub>2</sub> distribution mediated by a voltage-sensing phosphatase (VSP) regulates sperm motility",
   jo:"Proc Natl Acad Sci USA", vp:"116:26020-26028", doi:"10.1073/pnas.1916867116"},
  {n:123, y:2020, au:"Nishio M, To Y, Maehama T, Aono Y, Otani J, Hikasa H, Kitagawa A, Mimori K, Sasaki T, Nishina H, Toyokuni S, Lydon JP, Nakao K, Mak TW, Kiyono T, Katabuchi H, Tashiro H, Suzuki A",
   ti:"Endogenous YAP1 activation drives immediate onset of cervical carcinoma in situ in mice",
   jo:"Cancer Sci", vp:"111:3576-3587", doi:"10.1111/cas.14581"},
  {n:124, y:2021, au:"Hashimoto D, Hirashima T, Yamamura H, Kataoka T, Fujimoto K, Hyuga T, Yoshiki A, Kimura K, Kuroki S, Tachibana M, Suzuki K, Yamamoto N, Morioka S, Sasaki T, Yamada G",
   ti:"Dynamic erectile responses of a novel penile organ model utilizing TPEM",
   jo:"Biol Reprod", vp:"104:875-886", doi:"10.1093/biolre/ioab011"},
  {n:125, y:2021, au:"Huang M, Koizumi A, Narita S, Nakanishi H, Sato H, Jasguna S, Nara T, Kanda S, Numakura K, Saito M, Satoh S, Nanjo H, Sasaki T, Habuchi T",
   ti:"Altering phosphoinositides in high-fat diet-associated prostate tumor xenograft growth",
   jo:"Med Comm", vp:"2021", doi:"10.1002/mco2.89"},
  {n:126, y:2022, au:"Kawasaki A, Sakai A, Nakanishi H, Hasegawa J, Taguchi T, Sasaki J, Arai H, Sasaki T, Igarashi M, Nakatsu F",
   ti:"PI4P/PS countertransport by ORP10 at ER-endosome membrane contact sites regulates endosome fission",
   jo:"J Cell Biol", vp:"221:e202103141", doi:"10.1083/jcb.202103141"},
  {n:127, y:2022, au:"Morioka S, Nakanishi H, Yamamoto T, Hasegawa J, Tokuda E, Hikita T, Sakihara T, Kugii Y, Oneyama C, Yamazaki M, Suzuki A, Sasaki J, Sasaki T",
   ti:"A mass spectrometric method for in-depth profiling phosphoinositide regioisomers and their disease-associated regulation",
   jo:"Nat Commun", vp:"13:83", doi:"10.1038/s41467-021-27648-z"},
  {n:128, y:2022, au:"Hasegawa J, Tokuda E, Yao Y, Sasaki T, Inoki K, Weisman LS",
   ti:"PP2A-dependent TFEB activation is blocked by PIKfyve-induced mTORC1 activity",
   jo:"Mol Biol Cell", vp:"33:ar26", doi:"10.1091/mbc.E21-06-0309"},
  {n:129, y:2022, au:"Kanemaru K, Shimozawa M, Kitamata M, Furuishi R, Kayano H, Sukawa Y, Chiba Y, Fukuyama T, Hasegawa J, Nakanishi H, Kishimoto T, Tsujita K, Tanaka K, Itoh T, Sasaki J, Sasaki T, Fukami K, Nakamura Y",
   ti:"Plasma membrane phosphatidylinositol (4,5)-bisphosphate is critical for determination of epithelial characteristics",
   jo:"Nat Commun", vp:"13:2347", doi:"10.1038/s41467-022-30061-9"},
  {n:130, y:2022, au:"Hashimoto D, Hirashima T, Yamamura H, Kataoka T, Fujimoto K, Hyuga T, Yoshiki A, Kimura K, Kuroki S, Tachibana M, Suzuki K, Yamamoto N, Morioka S, Sasaki T, Yamada G",
   ti:"Establishment of mouse line showing inducible priapism-like phenotypes",
   jo:"Reprod Med Biol", vp:"2022", doi:"10.1002/rmb2.12472"},
  {n:131, y:2022, au:"Shiraishi Y, Maehama T, Nishio M, Otani J, Hikasa H, Mak TW, Sasaki T, Honma T, Kondoh Y, Osada H, Yoshida M, Fujisawa M, Suzuki A",
   ti:"N-(3,4-dimethoxyphenethyl)-6-methyl-2,3,4,9-tetrahydro-1H-carbazol-1-amine inhibits bladder cancer progression by suppressing YAP1/TAZ",
   jo:"Genes Cells", vp:"27:602-612", doi:"10.1111/gtc.12979"},
  {n:132, y:2022, au:"Ayukawa T, Akiyama M, Hozumi Y, Ishimoto K, Sasaki J, Senoo H, Sasaki T, Yamazaki M",
   ti:"Tissue flow regulates planar cell polarity independently of the Frizzled core pathway",
   jo:"Cell Rep", vp:"40:111388", doi:"10.1016/j.celrep.2022.111388"},
  {n:133, y:2023, au:"Kiyoki Y, Kato T, Kito S, Matsuzaka T, Morioka S, Sasaki J, Makishima K, Sakamoto T, Nishikii H, Obara N, Sakata-Yanagimoto M, Sasaki T, Shimano H, Chiba S",
   ti:"The fatty acid elongase Elovl6 is crucial for hematopoietic stem cell engraftment and leukemia propagation",
   jo:"Leukemia", vp:"37:910-913", doi:"10.1038/s41375-023-01842-y"},
  {n:134, y:2023, au:"Iguchi A, Takatori S, Kimura S, Hori Y, Sasaki J, Saito T, Saido T, Ikezu T, Takai T, Sasaki T, Tomita T",
   ti:"INPP5D modulates TREM2 loss-of-function phenotypes in a mouse model of Alzheimer disease",
   jo:"iScience", vp:"26:106375", doi:"10.1016/j.isci.2023.106375"},
  {n:135, y:2023, au:"Miyake T, Inoue Y, Shao X, Seta T, Aoki Y, Nguyen Pham KT, Shichino Y, Sasaki J, Sasaki T, Ikawa M, Yamaguchi Y, Okamura H, Iwasaki S, Doi M",
   ti:"Minimal upstream open reading frame of Per2 mediates phase fitness of the circadian clock to day/night physiological body temperature rhythm",
   jo:"Cell Rep", vp:"42:112157", doi:"10.1016/j.celrep.2023.112157"},
  {n:136, y:2023, au:"Tran DM, Yoshioka N, Bizen N, Mori-Ochiai Y, Yano M, Yanai S, Hasegawa J, Miyashita S, Hoshino M, Sasaki J, Sasaki T, Takebayashi H",
   ti:"Attenuated cerebellar phenotypes in Inpp4a truncation mutants with preserved phosphatase activity",
   jo:"Dis Model Mech", vp:"16:dmm050169", doi:"10.1242/dmm.050169"},
  {n:137, y:2023, au:"Arihisa W, Kondo T, Yamaguchi K, Matsumoto J, Nakanishi H, Kunii Y, Akatsu H, Hino M, Hashizume Y, Sato S, Sato S, Niwa SI, Yabe H, Sasaki T, Shigenobu S, Setou M",
   ti:"Lipid-correlated alterations in the transcriptome are enriched in several specific pathways in the postmortem prefrontal cortex of Japanese patients with schizophrenia",
   jo:"Neuropsychopharmacol Rep", vp:"43:403-413", doi:"10.1002/npr2.12368"},
  {n:138, y:2023, au:"Chessa TAM, Jung P, Anwar A, Suire S, Anderson KE, Barneda D, Kielkowska A, Sadiq BA, Lai IW, Felisbino S, Turnham DJ, Pearson HB, Phillips WA, Sasaki J, Sasaki T, Oxley D, Spensberger D, Segonds-Pichon A, Wilson M, Walker S, Okkenhaug H, Cosulich S, Hawkins PT, Stephens LR",
   ti:"PLEKHS1 drives PI3Ks and remodels pathway homeostasis in PTEN-null prostate",
   jo:"Mol Cell", vp:"83:2991-3009", doi:"10.1016/j.molcel.2023.07.015"},
  {n:139, y:2024, au:"Kofuji S, Wolfe K, Sumita K, Kageyama S, Yoshino H, Hirota Y, Ogawa-Iio A, Kanoh H, Sasaki M, Kofuji K, Davis MI, Pragani R, Shen M, Boxer MB, Nakatsu F, Nigorikawa K, Sasaki T, Takeuchi K, Senda T, Kim SM, Edinger AL, Simeonov A, Sasaki AT",
   ti:"A high dose KRP203 induces cytoplasmic vacuoles associated with altered phosphoinositide segregation and endosome expansion",
   jo:"Biochem Biophys Res Commun", vp:"718:149981", doi:"10.1016/j.bbrc.2024.149981"},
  {n:140, y:2024, au:"Oikawa T, Hasegawa J, Handa H, Ohnishi N, Onodera Y, Hashimoto A, Sasaki J, Sasaki T, Ueda K, Sabe H",
   ti:"p53 ensures the normal behavior and modification of G1/S-specific histone H3.1 in the nucleus",
   jo:"Life Sci Alliance", vp:"7:e202402835", doi:"10.26508/lsa.202402835"},
  {n:141, y:2024, au:"Kawai T, Morioka S, Miyata H, Andriani RT, Akter S, Toma G, Nakagawa T, Oyama Y, Iida-Norita R, Sasaki J, Watanabe M, Sakimura K, Ikawa M, Sasaki T, Okamura Y",
   ti:"The significance of electrical signals in maturing spermatozoa for phosphoinositide regulation through voltage-sensing phosphatase",
   jo:"Nat Commun", vp:"15:7289", doi:"10.1038/s41467-024-51755-2"},
  {n:142, y:2025, au:"Tsuji T, Hasegawa J, Sasaki T, Fujimoto T",
   ti:"Definition of phosphatidylinositol 4,5-bisphosphate distribution by freeze-fracture replica labeling",
   jo:"J Cell Biol", vp:"224:e202311067", doi:"10.1083/jcb.202311067"},
  {n:143, y:2025, au:"Ogawa Y, Tsuchiya I, Yanai S, Baba T, Morohashi KI, Sasaki T, Sasaki J, Terao M, Tsuji-Hosokawa A, Takada S",
   ti:"GATA4 binding to the Sox9 enhancer mXYSRa/Enh13 is critical for testis differentiation in mouse",
   jo:"Commun Biol", vp:"8:81", doi:"10.1038/s42003-025-07504-2"},
  {n:144, y:2025, au:"Wu JZ, Pemberton JG, Morioka S, Sasaki J, Bablani P, Sasaki T, Balla T, Grinstein S, Freeman SA",
   ti:"Sorting nexin 10 regulates lysosomal ionic homeostasis via ClC-7 by controlling PI(3,5)P<sub>2</sub>",
   jo:"J Cell Biol", vp:"224:e202408174", doi:"10.1083/jcb.202408174"},
  {n:145, y:2025, au:"Nishio M, Yamaguchi K, Otani J, Yuguchi K, Kohno D, Sasaki T, Kitamura T, Shinohara M, Soga T, Kawamura K, Sasaki AT, Oshima M, Hikasa H, Woo M, Sasaki T, Nishina H, Nakao K, Maehama T, Suzuki A",
   ti:"MOB1 deletion in murine mature adipocytes ameliorates obesity and diabetes",
   jo:"Proc Natl Acad Sci USA", vp:"122:e2424741122", doi:"10.1073/pnas.2424741122"},
  {n:146, y:2025, au:"Zhou X, van der Stoel MM, Kaptan S, Li H, Li S, Hölttä M, Vihinen H, Jokitalo E, Thiele C, Pietiläinen O, Morioka S, Sasaki J, Sasaki T, Vattulainen I, Ikonen E",
   ti:"Control of Golgi-V-ATPase through Sac1-dependent co-regulation of PI(4)P and cholesterol",
   jo:"Nat Commun", vp:"16:7808", doi:"10.1038/s41467-025-63125-7"},
  {n:147, y:2025, au:"Watanabe R, Morii M, Yamagata K, Ebihara T, Sasaki T, Mezaki Y, Mizuno M",
   ti:"100% Fish oil-based lipid emulsion inhibits hepatic stellate cell activation via suppression of the TGF-β1 autocrine signaling",
   jo:"Hum Cell", vp:"38:153", doi:"10.1007/s13577-025-01283-y"},
  {n:148, y:2025, au:"Yanai S, Sasaki J, Lee-Okada HC, Takahashi F, Kikuchi Y, Morioka S, Yamamoto T, Yuguchi K, Oikawa M, Kajiho H, Baba T, Yokoyama C, Morohashi KI, Suzuki A, Yokomizo T, Sasaki T",
   ti:"Adrenal lipoma formation via PI(3,4,5)P<sub>3</sub>/AKT-dependent transdifferentiation of adrenocortical cells into adipocytes",
   jo:"Proc Natl Acad Sci USA", vp:"122:e2510306122", doi:"10.1073/pnas.2510306122"},
  {n:149, y:2025, au:"Sako K, Morimoto Y, Morioka S, Hasegawa J, Nakajima H, Fukumoto M, Nishida Y, Shintani Y, Sasaki J, Sasaki T, Kikuchi K, Mochizuki N",
   ti:"Cells adapt to extracellular acidic pH through TM9SF3-mediated PI(4,5)P<sub>2</sub> flop",
   jo:"Nat Commun", vp:"16:8852", doi:"10.1038/s41467-025-63524-w"},
  {n:150, y:2025, au:"Mikawa T, Kameda M, Ikari S, Shibata E, Liu S, Miyagawa S, Ono K, Ito T, Yoshizawa A, Sugimoto M, Shibuya S, Shimizu T, Almunia J, Ogiso N, Revêchon G, Palazzo A, Bernard D, Kanda H, Soga T, Takubo K, Morioka S, Sasaki J, Sasaki T, Itamoto A, Fujii T, Seno H, Inagaki N, Kondoh H",
   ti:"Abrogation of aberrant glycolytic interactions eliminates senescent cells and alleviates aging-related dysfunctions",
   jo:"Signal Transduct Target Ther", vp:"10:402", doi:"10.1038/s41392-025-02502-6"},
  {n:151, y:2026, au:"Kawaguchi R, Miyakoshi T, Yoshimoto A, Hosoya S, Kugii Y, Sasaki T, Suzuki N, Ohkawa R",
   ti:"Homocysteine thiolactone affects paraoxonase 1 activity via altered paraoxonase 1 distribution on high-density lipoprotein particles",
   jo:"Biosci Rep", vp:"46:BSR20253768", doi:"10.1042/BSR20253768"},
  {n:152, y:2026, au:"Toyoshima A, Noguchi N, Suzuki T, Kuroki T, Kagaya M, Oda F, Kono M, Sasaki J, Sasaki T, Saeki H, Osada SI",
   ti:"PI3Kγ deficiency suppresses cutaneous squamous cell carcinoma formation by modulating the tumour microenvironment rather than by directly regulating keratinocyte proliferation",
   jo:"Exp Dermatol", vp:"35:e70219", doi:"10.1111/exd.70219"},
  {n:153, y:2026, au:"Kawahara T, Tani Y, Nawa N, Morioka S, Kajiho H, Sasaki J, Sasaki T, Fujiwara T",
   ti:"Circulating phospholipid species and internet addiction severity in Japanese adolescents: a pilot lipidomics study",
   jo:"Front Psychiatry", vp:"17:1751247", doi:"10.3389/fpsyt.2026.1751247"},
  {n:154, y:2026, au:"Kikuchi Y, Kajiho H, Hasegawa J, Mochida Y, Uchida S, Sasaki J, Sasaki T",
   ti:"Phosphatidylinositol 3,4-bisphosphate emerges as a lipid mediator linking oxidative stress to DNA damage",
   jo:"J Biochem", vp:"mvag027", doi:"10.1093/jb/mvag027"},
  {n:157, y:2026, au:"Shoji T, Shinojima A, Kishimoto T, Sato K, Ikegami N, Yumoto E, Shindo R, Uchida Y, Kusumi S, Koga D, Yamamoto E, Hirano Y, Ogino R, Shibata H, Izawa K, Yasumi T, Sato R, Nakayama J, Higashiyama S, Hasegawa J, Kajiho H, Sasaki T, Kuchitsu Y, Taguchi T",
   ti:"A PI(3,5)P<sub>2</sub>/CHMP4B axis on lysosomes is essential for microautophagic degradation of STING",
   jo:"Nat Commun", vp:"17:4602", doi:"10.1038/s41467-026-72828-4"},
  {n:156, y:2026, au:"Chen J, Kofuji S, Kusaba M, Abe K, Sasaki T, Ishitani T, Nishina H",
   ti:"Identification of gradual aging and late-onset aging markers using male African turquoise killifish",
   jo:"Sci Rep", vp:"2026", doi:"10.1038/s41598-026-50085-1"},
  {n:155, y:2026, au:"Otani J, Nishio M, Tokita R, Hikasa H, Nishimori M, Dan S, Naguro I, Ichijo H, Miyanishi M, Sasaki T, Nishina H, Mak TW, Maehama T, Suzuki A",
   ti:"SAMD4 represses VGLL4 mRNA to activate TEAD and promote cancer progression",
   jo:"Oncogene", vp:"2026", doi:"10.1038/s41388-026-03778-w"},
];

// ── REVIEW DATA ──────────────────────────────────────────────────────────────
const reviews = [
  {n:1,  y:2001, au:"Penninger J, Irie-Sasaki J, Sasaki T, Olivera-dos-Santos A",
   ti:"CD45: new jobs for an old acquaintance",
   jo:"Nat Immunol", vp:"2:389-396", doi:"10.1038/87687"},
  {n:2,  y:2001, au:"Sasaki T, Irie-Sasaki J, Penninger J",
   ti:"New insights into the transmembrane protein tyrosine phosphatase CD45",
   jo:"Int J Biochem Cell Biol", vp:"33:1041-1046", doi:"10.1016/s1357-2725(01)00075-9"},
  {n:3,  y:2002, au:"Sasaki T, Suzuki A, Sasaki J, Penninger J",
   ti:"Phosphoinositide 3-kinases in immunity: lessons from knockout mice",
   jo:"J Biochem", vp:"131:495-501", doi:"10.1093/oxfordjournals.jbchem.a003126"},
  {n:4,  y:2003, au:"Irie-Sasaki J, Sasaki T, Penninger J",
   ti:"CD45-regulated signaling pathways",
   jo:"Curr Top Med Chem", vp:"3:783-796", doi:"10.2174/1568026033452339"},
  {n:5,  y:2003, au:"Kishimoto H, Hamada K, Saunders M, Backman S, Sasaki T, Nakano T, Mak T, Suzuki A",
   ti:"Physiological functions of Pten in mouse tissues",
   jo:"Cell Struct Funct", vp:"28:11-21", doi:"10.1247/csf.28.11"},
  {n:6,  y:2004, au:"Suzuki A, Sasaki T, Mak T, Nakano T",
   ti:"Functional analysis of the tumor suppressor gene PTEN in murine B cells and keratinocytes",
   jo:"Biochem Soc Trans", vp:"32:362-365", doi:"10.1042/bst0320362"},
  {n:7,  y:2007, au:"Suzuki A, Hamada K, Sasaki T, Mak T, Nakano T",
   ti:"Role of Pten/PI3K pathway in endothelial cells",
   jo:"Biochem Soc Trans", vp:"35:172-176", doi:"10.1042/BST0350172"},
  {n:8,  y:2007, au:"Sasaki T, Sasaki J, Watanabe K, Suzuki A",
   ti:"Non-invasive visualization of the lipid product of class I PI3K in transgenic mouse models",
   jo:"Biochem Soc Trans", vp:"35:245-248", doi:""},
  {n:9,  y:2007, au:"Sasaki T, Sasaki J, Sakai T, Takasuga S, Suzuki A",
   ti:"The physiology of phosphoinositides",
   jo:"Biol Pharm Bull", vp:"30:1599-1604", doi:"10.1248/bpb.30.1599"},
  {n:10, y:2008, au:"Suzuki A, Nakano T, Mak T, Sasaki T",
   ti:"Portrait of PTEN: message from mutant mice",
   jo:"Cancer Sci", vp:"99:209-213", doi:"10.1111/j.1349-7006.2007.00670.x"},
  {n:11, y:2009, au:"Sasaki T, Takasuga S, Sasaki J, Kofuji S, Eguchi S, Yamazaki M, Suzuki A",
   ti:"Mammalian phosphoinositide kinases and phosphatases",
   jo:"Prog Lipid Res", vp:"48:307-343", doi:"10.1016/j.plipres.2009.06.001"},
  {n:12, y:2010, au:"Takeda M, Ito W, Tanabe M, Ueki S, Kihara J, Kato H, Tanigai T, Kayaba H, Sasaki T, Chihara J",
   ti:"The pathophysiological roles of PI3Ks and therapeutic potential of selective inhibitors in allergic inflammation",
   jo:"Int Arch Allergy Immunol", vp:"152:90-95", doi:"10.1159/000312132"},
  {n:13, y:2012, au:"Suzuki A, Kogo R, Kawahara K, Sasaki M, Nishio M, Maehama T, Sasaki T, Mimori K, Mori M",
   ti:"A new PICTure of nucleolar stress",
   jo:"Cancer Sci", vp:"103:209-213", doi:""},
  {n:14, y:2013, au:"Takasuga S, Sasaki T",
   ti:"Phosphatidylinositol-3,5-bisphosphate: metabolism and physiological functions",
   jo:"J Biochem", vp:"154:211-218", doi:"10.1093/jb/mvt064"},
  {n:15, y:2025, au:"Takeuchi K, Nagase L, Kageyama S, Kanoh H, Oshima M, Ogawa-Iio A, Ikeda Y, Fujii Y, Kondo S, Osaka N, Masuda T, Ishihara T, Nakamura Y, Hirota Y, Sasaki T, Senda T, Sasaki AT",
   ti:"PI5P4K inhibitors: promising opportunities and challenges",
   jo:"FEBS J", vp:"2025", doi:""},
  {n:16, y:2025, au:"Kajiho H, Morioka S, Sasaki J, Sasaki T",
   ti:"Spatiotemporal and quantitative analyses of phosphoinositides — fluorescent probe- and mass spectrometry-based approaches",
   jo:"FEBS Lett", vp:"2025", doi:"10.1002/1873-3468.70200"},
];
